server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/RestroMind
    username: postgres
    password: pratiksha
    driver-class-name: org.postgresql.Driver
  flyway:
    schemas: restromind_auth
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: restromind_auth
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

jwt:
  secret: restromind-super-secret-key-change-in-production-min-32-chars
  access-token-ttl-ms: 900000
  refresh-token-ttl-ms: 604800000
